## 8. Tarea 

### 1. Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 8 gramos de proteína y 6 gramos de grasa. Así mismo, no se debe tener más de 2 gramos de fibra y 0.4 gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, para simplificar la notación se van a nombrar las siguientes variables: 

$x_1:$ Gramos de pollo  
$x_2:$ Gramos de carne  
$x_3:$ Gramos de cordero  
$x_4:$ Gramos de arroz  
$x_5:$ Gramos de trigo  
$x_6:$ Gramos de gel  

Con los datos, se puede plantear la función objetivo, está dada por la siguiente expresión:

$$\min 0.013 x_1 + 0.008 x_2 + 0.010 x_3 + 0.002 x_4 + 0.005 x_5 + 0.001 x_6$$

Las restricciones estarían dadas por el siguiente conjunto de ecuaciones:

$x_1+x_2+x_3+x_4+x_5+x_6=100$  

$(10.0 x_1+ 20.0 x_2+ 15.0 x_3+ 00.0 x_4+ 04.0 x_5+ 00.0 x_6)/100 \geq 8.0$  

$(08.0 x_1+ 10.0 x_2+ 11.0 x_3+ 01.0 x_4+ 01.0 x_5+ 00.0 x_6)/100 \geq 6.0$  

$(00.1 x_1+ 00.5 x_2+ 00.5 x_3+ 10.0 x_4+ 15.0 x_5+ 00.0 x_6)/100 \leq 2.0$  

$(00.2 x_1+ 00.5 x_2+ 00.7 x_3+ 00.2 x_4+ 00.8 x_5+ 00.0 x_6)/100 \leq 0.4$  

La primer condición asegura que la cantidad de productos que se usará cumple con los 100 gramos. Las siguientes sólo siguen los lineamientos planteados para cumplir con los requisitos nutrimentales.

In [11]:
import numpy as np 
from scipy import optimize as opt 

In [22]:
c = np.array([0.013,0.008,0.10,0.002,0.005,0.001])
A_ineq = np.array([[-10,-20,-15,0,-4,0],
                   [-8,-10,-11,-1,-1,0],
                   [0.1,0.5,0.5,10,15,0],
                   [0.2,0.5,0.7,0.2,0.8,0]])
b_ineq = np.array([-800,-600,200,40])
Ae = np.array([[1,1,1,1,1,1]])
Be = np.array([100])

In [24]:
sol = opt.linprog (c=c, A_ub=A_ineq, b_ub=b_ineq, A_eq=Ae, b_eq=Be)

In [27]:
sol

     con: array([1.45893608e-08])
     fun: 0.5200000383542183
 message: 'Optimization terminated successfully.'
     nit: 12
   slack: array([4.00000023e+02, 1.89291600e-05, 1.69999902e+02, 9.99999656e+00])
  status: 0
 success: True
       x: array([1.17503789e-06, 6.00000000e+01, 8.60216988e-08, 6.14972360e-06,
       2.39377423e-06, 3.99999902e+01])

### 2. Otro problema de transporte

Referencia: https://relopezbriega.github.io/blog/2017/01/18/problemas-de-optimizacion-con-python/

Supongamos que tenemos que enviar cajas de cervezas de 2 cervecerías (Modelo y Cuauhtémoc Moctezuma) a 5 bares de acuerdo al siguiente gráfico:

<img style="float: center; margin: 0px 0px 15px 15px;" src="https://relopezbriega.github.io/images/Trans_problem.png" width="500px" height="150px" />

Asimismo, supongamos que nuestro gerente financiero nos informa que el costo de transporte por caja de cada ruta se conforma de acuerdo a la siguiente tabla:

In [36]:
import pandas as pd
info = pd.DataFrame({'Bar1': [2, 3], 'Bar2': [4, 1], 'Bar3': [5, 3], 'Bar4': [2, 2], 'Bar5': [1, 3]}, index = ['CerveceriaA', 'CerveceriaB'])
info

Bar1  Bar2  Bar3  Bar4  Bar5
CerveceriaA     2     4     5     2     1
CerveceriaB     3     1     3     2     3

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada cervecería (en cajas de cerveza) y cada bar, las cuales se detallan en el gráfico de más arriba.

Sean:
- $x_i$ cajas transportadas de la cervecería A al Bar $i$,
- $x_{i+5}$ cajas transportadas de la cervecería B al Bar $i$.

La tarea consiste en plantear el problema de minimizar el costo de transporte de la forma vista y resolverlo con `linprog`.

Deben crear un notebook de jupyter (archivo .ipynb) y llamarlo Tarea4_ApellidoNombre, y subirlo a moodle.

**Definir fecha**

In [37]:
import numpy as np 

In [55]:
c = np.array([2,4,5,2,1,3,1,3,2,3]) 
A = np.array([[-1,0,0,0,0,-1,0,0,0,0],
             [0,-1,0,0,0,0,-1,0,0,0],
             [0,0,-1,0,0,0,0,-1,0,0],
             [0,0,0,-1,0,0,0,0,-1,0],
             [0,0,0,0,-1,0,0,0,0,-1],
             [1,1,1,1,1,0,0,0,0,0],
             [0,0,0,0,0,1,1,1,1,1]])
b = np.array ([-500,-900,-1800,-200,-700,1000,4000]) 
c,A,b

(array([2, 4, 5, 2, 1, 3, 1, 3, 2, 3]),
 array([[-1,  0,  0,  0,  0, -1,  0,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  0, -1,  0,  0,  0],
        [ 0,  0, -1,  0,  0,  0,  0, -1,  0,  0],
        [ 0,  0,  0, -1,  0,  0,  0,  0, -1,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  0,  0, -1],
        [ 1,  1,  1,  1,  1,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1]]),
 array([ -500,  -900, -1800,  -200,  -700,  1000,  4000]))

In [56]:
solucion = opt.linprog(c=c, A_ub=A, b_ub=b)

In [57]:
solucion

     con: array([], dtype=float64)
     fun: 8599.999737887745
 message: 'Optimization terminated successfully.'
     nit: 7
   slack: array([-1.76922439e-05, -2.72044543e-05, -6.74372143e-05, -5.32016659e-06,
       -2.38846903e-05,  4.06969139e-05,  9.00000101e+02])
  status: 0
 success: True
       x: array([2.99999987e+02, 2.04475512e-06, 1.19852270e-06, 9.54759464e-06,
       6.99999959e+02, 1.99999995e+02, 8.99999971e+02, 1.79999993e+03,
       1.99999985e+02, 1.68711902e-05])